source 'https://rubygems.org'

gem 'sinatra'
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter', git: 'https://github.com/nextgearcapital/activerecord-sqlserver-adapter.git'
gem 'thin'
gem 'sinatra-contrib'
gem 'rack'
gem 'json_spec'
gem 'capistrano', '~> 3.1.0'
gem 'capistrano-rvm'
gem 'capistrano-bundler'

group :production do
  gem 'puma'
end
